### ISSUE TITLE
Can't find module through npm installation

### ISSUE THREAD

**Issue by benhowdle89** [felixrieseberg/React-Spreadsheet-Component#11]
Installed this using `npm install`, I can see it in my `node_modules` folder, but when I import like so:

`import Spreadsheet from 'react-spreadsheet-component'`, I get the error `Error: cannot find module 'react-spreadsheet-component'`. Any idea why this might be?

**Comment by anurag77** [comment]
+1 , having the same issue. All samples assume this code is local in ./src folder however there is nothing to load it from node_modules. I even tried giving the full path the node_modules/src/spreadsheet.js but no luck

**Comment by benhowdle89** [comment]
@anurag77 My deadline was pretty tight, so I ended up using this: https://github.com/arqex/react-json-table which is really flexible!

**Comment by felixrieseberg** [comment]
Hey everyone - sorry for the long delay here: The name of the component to npm is `react-spreadsheet` (mostly because that is what we used to call it) - so you'll need to `require('react-spreadsheet')` or `import Spreadsheet from `react-spreadsheet`.

**Comment by felixrieseberg** [comment]
This isn't documented at all though, so that's clearly my fault - I'll update the readme!

**Comment by felixrieseberg** [comment]
I'm an idiot - disregard all previous info. Fix incoming.

**Comment by felixrieseberg** [comment]
Fixed!
