### ISSUE TITLE
Module not found: Cannot resolve module 'mousetrap' in .../spreadsheet  @ .../spreadsheet/dispatcher.js

### ISSUE THREAD

**Issue by thomaswrenn** [felixrieseberg/React-Spreadsheet-Component#2]
We just added mousetrap ~1.5.3 to our package.json and that fixed our builds. Haven't tested yet. We had tested with ~1.5.2 back when we first built it.

**Comment by felixrieseberg** [comment]
Thanks! I'll add that right away :)

**Comment by felixrieseberg** [comment]
Thanks, fixed!
